
# %% grid search by SARGOLI
# %%%random forest

import sys 
sys.path.insert(0,r'E:\\GitLab\\credit-risk-ai\\') # path of risk_utils
from risk_utilsV2 import *
import pandas as pd
import pickle
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import itertools
import time
from sklearn.metrics import classification_report
import itertools


# --------------------
# -------------------------------------------------------------------------------------
# --------------------





rf_params = {"max_depth": [1,3, None],
             "n_estimators": [10,100,250],
              "max_features": [2,8,11,40],
              "min_samples_split": [2,8,11,40],
              "min_samples_leaf": [2,8,11,40],
              "bootstrap": [True, False],
              "criterion": ["gini", "entropy","log_loss"]}


# =============================================================================
#  CONFIG
config = {
    'out_path': r'F:\OUT\\hyper_rf\\',            # models and data are saved in that folder
    
    # for train 
    'train_dataset':r'F:\RISK\DATA\train\sherkati\\sherkati_traindata.csv',
    
    # for evaluate
    'test_df': r'F:\RISK\DATA\train\sherkati\sherkati_testdata.csv',
    
    # needed columns                
    'without_facility_stacking_cols': ['BIRTHDATE', 'OBSERVATION_DATE', 'CUSTGROUP', 'IND_CNTRCT_CNT_1Y', 'IND_CNTRCT_CNT_3Y', 'IND_CNTRCT_JARI_CNT_1Y', 'IND_CNTRCT_JARI_CNT_3Y', 'IND_CNTRCT_SRRSD_CNT_1Y', 'IND_CNTRCT_SRRSD_CNT_3Y', 'IND_CNTRCT_MVQ_CNT_1Y', 'IND_CNTRCT_MVQ_CNT_3Y', 'IND_CNTRCT_MSHKK_CNT_1Y', 'IND_CNTRCT_MSHKK_CNT_3Y', 'IND_CNTRCT_TDBT_SUM_MAX_1Y', 'IND_CNTRCT_TDBT_SUM_MAX_3Y', 'IND_CNTRCT_TDBT_SUM_JARI_MAX_1Y', 'IND_CNTRCT_TDBT_SUM_JARI_MAX_3Y', 'IND_CNTRCT_TDBT_SUM_SRRSD_MAX_1Y', 'IND_CNTRCT_TDBT_SUM_SRRSD_MAX_3Y', 'IND_CNTRCT_TDBT_SUM_MVQ_MAX_1Y', 'IND_CNTRCT_TDBT_SUM_MVQ_MAX_3Y', 'IND_CNTRCT_TDBT_SUM_MSHKK_MAX_1Y', 'IND_CNTRCT_TDBT_SUM_MSHKK_MAX_3Y', 'IND_CNTRCT_PAY_MAX_1Y', 'IND_CNTRCT_PAY_MAX_3Y', 'IND_CNTRCT_SMPAY_MAX_JARI_MAX_1Y', 'IND_CNTRCT_SMPAY_MAX_JARI_MAX_3Y', 'IND_CNTRCT_SMPAY_MAX_MSHKK_SUM_1Y', 'IND_CNTRCT_SMPAY_MAX_MSHKK_SUM_3Y', 'ACC_BLNC_EOM_MAX_1Y', 'ACC_BLNC_EOM_AVG_1Y', 'ACC_FREE_BLNC_EOM_AVG_1Y', 'ACC_MDL_MON_AVG_1Y', 'ACC_COST_BLNC_EOM_MAX_1Y', 'ACC_FREE_BLNC_EOM_MAX_1Y', 'ACC_COST_BLNC_EOM_AVG_1Y', 'ACC_COST_MDL_MON_AVG_1Y', 'ACC_FREE_MDL_MON_AVG_1Y', 'ACC_COST_MDL_MON_MAX_1Y', 'ACC_FREE_MDL_MON_MAX_1Y', 'ACC_MDL_MON_MAX_1Y', 'ACC_BLNC_EOM_MAX_6M', 'ACC_BLNC_EOM_AVG_6M', 'ACC_FREE_BLNC_EOM_AVG_6M', 'ACC_MDL_MON_AVG_6M', 'ACC_COST_BLNC_EOM_MAX_6M', 'ACC_FREE_BLNC_EOM_MAX_6M', 'ACC_COST_BLNC_EOM_AVG_6M', 'ACC_COST_MDL_MON_AVG_6M', 'ACC_FREE_MDL_MON_AVG_6M', 'ACC_COST_MDL_MON_MAX_6M', 'ACC_FREE_MDL_MON_MAX_6M', 'ACC_MDL_MON_MAX_6M', 'ACC_BLNC_EOM_MAX_3M', 'ACC_BLNC_EOM_AVG_3M', 'ACC_FREE_BLNC_EOM_AVG_3M', 'ACC_MDL_MON_AVG_3M', 'ACC_COST_BLNC_EOM_MAX_3M', 'ACC_FREE_BLNC_EOM_MAX_3M', 'ACC_COST_BLNC_EOM_AVG_3M', 'ACC_COST_MDL_MON_AVG_3M', 'ACC_FREE_MDL_MON_AVG_3M', 'ACC_COST_MDL_MON_MAX_3M', 'ACC_FREE_MDL_MON_MAX_3M', 'ACC_MDL_MON_MAX_3M', 'TRN_CR_CNT_1Y', 'TRN_ACC_COST_CR_CNT_1Y', 'TRN_ACC_FREE_CR_CNT_1Y', 'TRN_CR_AMNT_SUM_1Y', 'TRN_ACC_COST_CR_AMNT_SUM_1Y', 'TRN_ACC_FREE_CR_AMNT_SUM_1Y', 'TRN_DB_CNT_1Y', 'TRN_ACC_COST_DB_CNT_1Y', 'TRN_ACC_FREE_DB_CNT_1Y', 'TRN_DB_AMNT_SUM_1Y', 'TRN_ACC_COST_DB_AMNT_SUM_1Y', 'TRN_ACC_FREE_DB_AMNT_SUM_1Y', 'TRN_CR_CNT_6M', 'TRN_ACC_COST_CR_CNT_6M', 'TRN_ACC_FREE_CR_CNT_6M', 'TRN_CR_AMNT_SUM_6M', 'TRN_ACC_COST_CR_AMNT_SUM_6M', 'TRN_ACC_FREE_CR_AMNT_SUM_6M', 'TRN_DB_CNT_6M', 'TRN_ACC_COST_DB_CNT_6M', 'TRN_ACC_FREE_DB_CNT_6M', 'TRN_DB_AMNT_SUM_6M', 'TRN_ACC_COST_DB_AMNT_SUM_6M', 'TRN_ACC_FREE_DB_AMNT_SUM_6M', 'TRN_CR_CNT_3M', 'TRN_ACC_COST_CR_CNT_3M', 'TRN_ACC_FREE_CR_CNT_3M', 'TRN_CR_AMNT_SUM_3M', 'TRN_ACC_COST_CR_AMNT_SUM_3M', 'TRN_ACC_FREE_CR_AMNT_SUM_3M', 'TRN_DB_CNT_3M', 'TRN_ACC_COST_DB_CNT_3M', 'TRN_ACC_FREE_DB_CNT_3M', 'TRN_DB_AMNT_SUM_3M', 'TRN_ACC_COST_DB_AMNT_SUM_3M', 'TRN_ACC_FREE_DB_AMNT_SUM_3M', 'CHQ_PASS_CNT_3Y', 'CHQ_PASS_AMNT_SUM_3Y', 'CHQ_RETURN_PASS_CNT_3Y', 'CHQ_RETURN_PASS_AMNT_SUM_3Y', 'CHQ_PASS_CNT_1Y', 'CHQ_PASS_AMNT_SUM_1Y', 'CHQ_RETURN_PASS_CNT_1Y', 'CHQ_RETURN_PASS_AMNT_SUM_1Y', 'CHQ_RETURN_AMNT_SUM_3Y', 'CHQ_RETURN_CNT_3Y', 'CHQ_RETURN_AMNT_SUM_1Y', 'CHQ_RETURN_CNT_1Y', 'CHQ_CHQBK_CNT_3Y', 'CHQ_CHQBK_CNT_1Y', 'CBI_INQUERY_RETURN_CHQ_CNT_3Y', 'CBI_RETURN_CHQ_CNT_3Y', 'CBI_RETURN_CHQ_MAX_3Y', 'CBI_RETURN_CHQ_SUM_3Y', 'CBI_RETURN_CHQ_AVG_3Y', 'CBI_INQUERY_RETURN_CHQ_CNT_1Y', 'CBI_RETURN_CHQ_CNT_1Y', 'CBI_RETURN_CHQ_MAX_1Y', 'CBI_RETURN_CHQ_SUM_1Y', 'CBI_RETURN_CHQ_AVG_1Y', 'FIRSTACCCREATEDATE', 'SEXTYPE', 'BIRTHCITYCODE'],
    'with_facility_stacking_cols': ['BIRTHDATE','OBSERVATION_DATE', 'CUSTGROUP', 'CNTRCT_GRNTNGDT_MIN', 'CNTRCT_PNLTYDBT_MAX_ZND_SUM_1Y', 'CNTRCT_PNLTYDBT_MAX_ZND_SUM_3Y', 'CNTRCT_PNLTYDBT_SUM_ZND_MAX_1Y', 'CNTRCT_PNLTYDBT_SUM_ZND_MAX_3Y', 'CNTRCT_PNLTYRCV_SUM_1Y', 'CNTRCT_PNLTYRCV_SUM_3Y', 'CNTRCT_PAY_SUM_1Y', 'CNTRCT_PAY_SUM_3Y', 'CNTRCT_PAY_MAX_1Y', 'CNTRCT_PAY_MAX_3Y', 'CNTRCT_TDBT_MSHKK_ZND_RATIO_AVG_1Y', 'CNTRCT_TDBT_MSHKK_ZND_RATIO_AVG_3Y', 'CNTRCT_TDBT_ZND_SUM_LAST', 'CNTRCT_SDBT_ZND_SUM_LAST', 'CNTRCT_TDBT_JARI_SUM_LAST', 'CNTRCT_SDBT_JARI_SUM_LAST', 'CNTRCT_TDBT_SQJARI_SUM_LAST', 'CNTRCT_SDBT_SQJARI_SUM_LAST', 'CNTRCT_TDBT_SRRSD_SUM_LAST', 'CNTRCT_SDBT_SRRSD_SUM_LAST', 'CNTRCT_TDBT_MVQ_SUM_LAST', 'CNTRCT_SDBT_MVQ_SUM_LAST', 'CNTRCT_TDBT_MSHKK_SUM_LAST', 'CNTRCT_SDBT_MSHKK_SUM_LAST', 'IND_CNTRCT_CNT_1Y', 'IND_CNTRCT_CNT_3Y', 'IND_CNTRCT_JARI_CNT_1Y', 'IND_CNTRCT_JARI_CNT_3Y', 'IND_CNTRCT_SRRSD_CNT_1Y', 'IND_CNTRCT_SRRSD_CNT_3Y', 'IND_CNTRCT_MVQ_CNT_1Y', 'IND_CNTRCT_MVQ_CNT_3Y', 'IND_CNTRCT_MSHKK_CNT_1Y', 'IND_CNTRCT_MSHKK_CNT_3Y', 'IND_CNTRCT_TDBT_SUM_MAX_1Y', 'IND_CNTRCT_TDBT_SUM_MAX_3Y', 'IND_CNTRCT_TDBT_SUM_JARI_MAX_1Y', 'IND_CNTRCT_TDBT_SUM_JARI_MAX_3Y', 'IND_CNTRCT_TDBT_SUM_SRRSD_MAX_1Y', 'IND_CNTRCT_TDBT_SUM_SRRSD_MAX_3Y', 'IND_CNTRCT_TDBT_SUM_MVQ_MAX_1Y', 'IND_CNTRCT_TDBT_SUM_MVQ_MAX_3Y', 'IND_CNTRCT_TDBT_SUM_MSHKK_MAX_1Y', 'IND_CNTRCT_TDBT_SUM_MSHKK_MAX_3Y', 'IND_CNTRCT_PAY_MAX_1Y', 'IND_CNTRCT_PAY_MAX_3Y', 'IND_CNTRCT_SMPAY_MAX_JARI_MAX_1Y', 'IND_CNTRCT_SMPAY_MAX_JARI_MAX_3Y', 'IND_CNTRCT_SMPAY_MAX_MSHKK_SUM_1Y', 'IND_CNTRCT_SMPAY_MAX_MSHKK_SUM_3Y', 'FCL_FCLTYSTS_MAX_1Y', 'FCL_FCLTYSTS_MAX_3Y', 'FCL_PAY_SUM_1Y', 'FCL_PAY_SUM_3Y', 'FCL_SMPAY_MAX_ZND_SUM_1Y', 'FCL_SMPAY_MAX_ZND_SUM_3Y', 'FCL_SMPAY_MAX_JARI_SUM_1Y', 'FCL_SMPAY_MAX_JARI_SUM_3Y', 'FCL_SMPAY_MAX_SQJARI_SUM_1Y', 'FCL_SMPAY_MAX_SQJARI_SUM_3Y', 'FCL_SMPAY_MAX_TSV_SUM_1Y', 'FCL_SMPAY_MAX_TSV_SUM_3Y', 'FCL_GRNTNGDT_CNT_1Y', 'FCL_GRNTNGDT_CNT_3Y', 'FCL_ZND_CNT_1Y', 'FCL_ZND_CNT_3Y', 'FCL_JARI_CNT_1Y', 'FCL_JARI_CNT_3Y', 'FCL_SQJARI_CNT_1Y', 'FCL_SQJARI_CNT_3Y', 'FCL_SRRSD_CNT_1Y', 'FCL_SRRSD_CNT_3Y', 'FCL_MVQ_CNT_1Y', 'FCL_MVQ_CNT_3Y', 'FCL_MSHKK_CNT_1Y', 'FCL_MSHKK_CNT_3Y', 'FCL_TSV_CNT_1Y', 'FCL_TSV_CNT_3Y', 'FCL_SRRSD_ENTRNC_NEG_CNT_1Y', 'FCL_SRRSD_ENTRNC_NEG_CNT_3Y', 'FCL_SRRSD_ENTRNC_POS_CNT_1Y', 'FCL_SRRSD_ENTRNC_POS_CNT_3Y', 'FCL_MVQ_ENTRNC_NEG_CNT_1Y', 'FCL_MVQ_ENTRNC_NEG_CNT_3Y', 'FCL_MSHKK_ENTRNC_NEG_CNT_1Y', 'FCL_MSHKK_ENTRNC_NEG_CNT_3Y', 'FCL_TDBT_MAX_JARI_SUM_1Y', 'FCL_TDBT_MAX_JARI_SUM_3Y', 'FCL_TDBT_MAX_SQJARI_SUM_1Y', 'FCL_TDBT_MAX_SQJARI_SUM_3Y', 'FCL_TDBT_MAX_MSHKK_SUM_1Y', 'FCL_TDBT_MAX_MSHKK_SUM_3Y', 'FCL_TDBT_SUM_ZND_MAX_1Y', 'FCL_TDBT_SUM_ZND_MAX_3Y', 'FCL_TDBT_SUM_JARI_MAX_1Y', 'FCL_TDBT_SUM_JARI_MAX_3Y', 'FCL_TDBT_SUM_SQJARI_MAX_1Y', 'FCL_TDBT_SUM_SQJARI_MAX_3Y', 'FCL_TDBT_SUM_MSHKK_MAX_1Y', 'FCL_TDBT_SUM_MSHKK_MAX_3Y', 'FCL_TDBT_SUM_TSV_MAX_1Y', 'FCL_TDBT_SUM_TSV_MAX_3Y', 'FCL_SDBT_MAX_ZND_SUM_1Y', 'FCL_SDBT_MAX_ZND_SUM_3Y', 'FCL_SDBT_MAX_JARI_SUM_1Y', 'FCL_SDBT_MAX_JARI_SUM_3Y', 'FCL_SDBT_MAX_SQJARI_SUM_1Y', 'FCL_SDBT_MAX_SQJARI_SUM_3Y', 'FCL_SDBT_MAX_SRRSD_SUM_1Y', 'FCL_SDBT_MAX_SRRSD_SUM_3Y', 'FCL_SDBT_MAX_MVQ_SUM_1Y', 'FCL_SDBT_MAX_MVQ_SUM_3Y', 'FCL_SDBT_MAX_TSV_SUM_1Y', 'FCL_SDBT_MAX_TSV_SUM_3Y', 'FCL_SDBT_SUM_ZND_MAX_1Y', 'FCL_SDBT_SUM_ZND_MAX_3Y', 'FCL_SDBT_SUM_JARI_MAX_1Y', 'FCL_SDBT_SUM_JARI_MAX_3Y', 'FCL_SDBT_SUM_SQJARI_MAX_1Y', 'FCL_SDBT_SUM_SQJARI_MAX_3Y', 'FCL_SDBT_SUM_SRRSD_MAX_1Y', 'FCL_SDBT_SUM_SRRSD_MAX_3Y', 'FCL_SDBT_SUM_MVQ_MAX_1Y', 'FCL_SDBT_SUM_MVQ_MAX_3Y', 'FCL_SDBT_SUM_TSV_MAX_1Y', 'FCL_SDBT_SUM_TSV_MAX_3Y', 'FCL_RCVAMNT_MAX_1Y', 'FCL_RCVAMNT_MAX_3Y', 'FCL_RCVAMNT_SUM_1Y', 'FCL_RCVAMNT_SUM_3Y', 'FCL_RCVAMNT_AVG_1Y', 'FCL_RCVAMNT_AVG_3Y', 'FCL_SDBT_SRRSD_SUM_TDBT_ZND_SUM_RATIO_AVG_1Y', 'FCL_SDBT_SRRSD_SUM_TDBT_ZND_SUM_RATIO_AVG_3Y', 'FCL_SDBT_MVQ_SUM_TDBT_ZND_SUM_RATIO_AVG_1Y', 'FCL_SDBT_MVQ_SUM_TDBT_ZND_SUM_RATIO_AVG_3Y', 'LC_GRN_CNT_1Y', 'LC_GRN_CNT_3Y', 'LC_GRN_GRNTNGDT_CNT_1Y', 'LC_GRN_GRNTNGDT_CNT_3Y', 'LC_GRN_ZABT_CNT_1Y', 'LC_GRN_ZABT_CNT_3Y', 'LC_GRN_GRNTNGDT_AMNT_MAX_SUM_1Y', 'LC_GRN_GRNTNGDT_AMNT_MAX_SUM_3Y', 'LC_GRN_AMNT_MAX_ZND_SUM_1Y', 'LC_GRN_AMNT_MAX_ZND_SUM_3Y', 'LC_GRN_ZABT_PAY_SUM_1Y', 'LC_GRN_ZABT_PAY_SUM_3Y', 'LC_GRN_TDBT_MAX_BDHKRN_SUM_1Y', 'LC_GRN_TDBT_MAX_BDHKRN_SUM_3Y', 'LC_GRN_TDBT_MAX_MSHKK_SUM_1Y', 'LC_GRN_TDBT_MAX_MSHKK_SUM_3Y', 'LC_GRN_TDBT_SUM_BDHKRN_MAX_1Y', 'LC_GRN_TDBT_SUM_BDHKRN_MAX_3Y', 'LC_GRN_TDBT_SUM_MSHKK_MAX_1Y', 'LC_GRN_TDBT_SUM_MSHKK_MAX_3Y', 'ACC_BLNC_EOM_MAX_1Y', 'ACC_BLNC_EOM_AVG_1Y', 'ACC_FREE_BLNC_EOM_AVG_1Y', 'ACC_MDL_MON_AVG_1Y', 'ACC_COST_BLNC_EOM_MAX_1Y', 'ACC_FREE_BLNC_EOM_MAX_1Y', 'ACC_COST_BLNC_EOM_AVG_1Y', 'ACC_COST_MDL_MON_AVG_1Y', 'ACC_FREE_MDL_MON_AVG_1Y', 'ACC_COST_MDL_MON_MAX_1Y', 'ACC_FREE_MDL_MON_MAX_1Y', 'ACC_MDL_MON_MAX_1Y', 'ACC_BLNC_EOM_MAX_6M', 'ACC_BLNC_EOM_AVG_6M', 'ACC_FREE_BLNC_EOM_AVG_6M', 'ACC_MDL_MON_AVG_6M', 'ACC_COST_BLNC_EOM_MAX_6M', 'ACC_FREE_BLNC_EOM_MAX_6M', 'ACC_COST_BLNC_EOM_AVG_6M', 'ACC_COST_MDL_MON_AVG_6M', 'ACC_FREE_MDL_MON_AVG_6M', 'ACC_COST_MDL_MON_MAX_6M', 'ACC_FREE_MDL_MON_MAX_6M', 'ACC_MDL_MON_MAX_6M', 'ACC_BLNC_EOM_MAX_3M', 'ACC_BLNC_EOM_AVG_3M', 'ACC_FREE_BLNC_EOM_AVG_3M', 'ACC_MDL_MON_AVG_3M', 'ACC_COST_BLNC_EOM_MAX_3M', 'ACC_FREE_BLNC_EOM_MAX_3M', 'ACC_COST_BLNC_EOM_AVG_3M', 'ACC_COST_MDL_MON_AVG_3M', 'ACC_FREE_MDL_MON_AVG_3M', 'ACC_COST_MDL_MON_MAX_3M', 'ACC_FREE_MDL_MON_MAX_3M', 'ACC_MDL_MON_MAX_3M', 'TRN_CR_CNT_1Y', 'TRN_ACC_COST_CR_CNT_1Y', 'TRN_ACC_FREE_CR_CNT_1Y', 'TRN_CR_AMNT_SUM_1Y', 'TRN_ACC_COST_CR_AMNT_SUM_1Y', 'TRN_ACC_FREE_CR_AMNT_SUM_1Y', 'TRN_DB_CNT_1Y', 'TRN_ACC_COST_DB_CNT_1Y', 'TRN_ACC_FREE_DB_CNT_1Y', 'TRN_DB_AMNT_SUM_1Y', 'TRN_ACC_COST_DB_AMNT_SUM_1Y', 'TRN_ACC_FREE_DB_AMNT_SUM_1Y', 'TRN_CR_CNT_6M', 'TRN_ACC_COST_CR_CNT_6M', 'TRN_ACC_FREE_CR_CNT_6M', 'TRN_CR_AMNT_SUM_6M', 'TRN_ACC_COST_CR_AMNT_SUM_6M', 'TRN_ACC_FREE_CR_AMNT_SUM_6M', 'TRN_DB_CNT_6M', 'TRN_ACC_COST_DB_CNT_6M', 'TRN_ACC_FREE_DB_CNT_6M', 'TRN_DB_AMNT_SUM_6M', 'TRN_ACC_COST_DB_AMNT_SUM_6M', 'TRN_ACC_FREE_DB_AMNT_SUM_6M', 'TRN_CR_CNT_3M', 'TRN_ACC_COST_CR_CNT_3M', 'TRN_ACC_FREE_CR_CNT_3M', 'TRN_CR_AMNT_SUM_3M', 'TRN_ACC_COST_CR_AMNT_SUM_3M', 'TRN_ACC_FREE_CR_AMNT_SUM_3M', 'TRN_DB_CNT_3M', 'TRN_ACC_COST_DB_CNT_3M', 'TRN_ACC_FREE_DB_CNT_3M', 'TRN_DB_AMNT_SUM_3M', 'TRN_ACC_COST_DB_AMNT_SUM_3M', 'TRN_ACC_FREE_DB_AMNT_SUM_3M', 'CHQ_PASS_CNT_3Y', 'CHQ_PASS_AMNT_SUM_3Y', 'CHQ_RETURN_PASS_CNT_3Y', 'CHQ_RETURN_PASS_AMNT_SUM_3Y', 'CHQ_PASS_CNT_1Y', 'CHQ_PASS_AMNT_SUM_1Y', 'CHQ_RETURN_PASS_CNT_1Y', 'CHQ_RETURN_PASS_AMNT_SUM_1Y', 'CHQ_RETURN_AMNT_SUM_3Y', 'CHQ_RETURN_CNT_3Y', 'CHQ_RETURN_AMNT_SUM_1Y', 'CHQ_RETURN_CNT_1Y', 'CHQ_CHQBK_CNT_3Y', 'CHQ_CHQBK_CNT_1Y', 'CBI_INQUERY_RETURN_CHQ_CNT_3Y', 'CBI_RETURN_CHQ_CNT_3Y', 'CBI_RETURN_CHQ_MAX_3Y', 'CBI_RETURN_CHQ_SUM_3Y', 'CBI_RETURN_CHQ_AVG_3Y', 'CBI_INQUERY_RETURN_CHQ_CNT_1Y', 'CBI_RETURN_CHQ_CNT_1Y', 'CBI_RETURN_CHQ_MAX_1Y', 'CBI_RETURN_CHQ_SUM_1Y', 'CBI_RETURN_CHQ_AVG_1Y', 'FIRSTACCCREATEDATE', 'SEXTYPE', 'BIRTHCITYCODE', 'CBI_CNTRCT_REQUEST_CNT_3Y', 'CBI_CNTRCT_CNTRCT_CNT_3Y', 'CBI_CNTRCT_ASL_MAX_MAX_3Y', 'CBI_CNTRCT_ASL_MAX_SUM_3Y', 'CBI_CNTRCT_BEDEHI_MAX_MAX_3Y', 'CBI_CNTRCT_SARRESID_MAX_MAX_3Y', 'CBI_CNTRCT_MOAVAQ_MAX_MAX_3Y', 'CBI_CNTRCT_MASHKUK_MAX_MAX_3Y', 'CBI_CNTRCT_REQUEST_CNT_1Y', 'CBI_CNTRCT_CNTRCT_CNT_1Y', 'CBI_CNTRCT_ASL_MAX_MAX_1Y', 'CBI_CNTRCT_ASL_MAX_SUM_1Y', 'CBI_CNTRCT_BEDEHI_MAX_MAX_1Y', 'CBI_CNTRCT_SARRESID_MAX_MAX_1Y', 'CBI_CNTRCT_MOAVAQ_MAX_MAX_1Y', 'CBI_CNTRCT_MASHKUK_MAX_MAX_1Y'],
    'cat_cols': ['CUSTGROUP', 'SEXTYPE', 'BIRTHCITYCODE'],
}
cols_ = config['without_facility_stacking_cols'] 
X, y = get_Xy(df_path=config['train_dataset'],cols=cols_)  
Xt, yt = get_Xy(df_path=config['test_df'],cols=cols_)  

# =============================================================================



par = list(itertools.product(*list(rf_params.values())))
print(len(par))





cont = []
for i in range(2350,len(par)):
    print(f' loop {i} start')
    rf_rf = RandomForestClassifier(max_depth = par[i][0],min_samples_split = par[i][3],
                                   min_samples_leaf = par[i][4],
                                   n_estimators=par[i][1],
                                   max_features=par[i][2],
                                   bootstrap=par[i][5],
                                   criterion=par[i][6],
                                   class_weight='balanced_subsample', n_jobs=-1, verbose = 0)
    
    
    rf_rf.fit(X,  np.ravel(y))
    
        



    
    
    
    out_y = evaluate_solo(model=rf_rf, test_path=config['test_df'],smote=False,cols=cols_,out_path=config['out_path'])

    report = classification_report(out_y.y_test_org, out_y.y_test_pred, output_dict=True)
    f10 = report['0']['f1-score']
    f11 = report['1']['f1-score']
    f = (f10 + f11) / 2 
    
    
    
    print(f'score: {f11} loop {i} DONE\n\n****\n{par[i]}\n---------------')
    if f11 > 0.64:
        get_metrics(y=out_y.y_test_org,y_pred=out_y['y_test_pred'],save_dir=config['out_path'],
                    title=f'{f11}____{i}_____rf_', plot=False)

            
    
    # joblib.dump(xgboost, f'{out_path}/{f11}_{model_name}_trainedModel_xg_.pkl')
